Adding the possibility to use mueller matrices as input for mcfost.
cpinte/mcfost pull request #57
Opened 2023-04-25 16:39 UTC by FMalaval

Adds and changes in the code to permit it to read mueller matrices to use in place of Mie calculations. One matrix representing the average matrix over the size distribution can be use as input, or one for each size particle considered in the simulation. For now, this option permit to use the matrices for only 1 considered wavelength.

2023-04-26 13:15 UTC, cpinte requested changes
Salut,
Je ne comprends pourquoi tu as supprime les fichiers avant de les remettre. Pourrais-tu faire un rebase pour fusionner les commits et eviter d'avoir des fichiers efaches puis remis dans le depot ?
Merci !

2023-04-26 14:45 UTC, FMalaval commented
Salut !


Parce que c'était plus simple, et que je ne savais pas trop comment m'y prendre de manière propre....
Oui pas de soucis, je viens de le faire normalement, mais je ne suis pas sûr de l'avoir fait correctement...

2023-05-02 02:25 UTC, cpinte commented
Salut,
Je vois encore 8 commits avec des delete et 1 avec upload. Tu as fait les changements ou tu vas les faire ?

2023-05-02 10:04 UTC, FMalaval commented
Je pensais l'avoir fait, mais je n'avait pas push les changements. Normalement c'est bon, et j'en ai aussi profité pour ajouter ton dernier commit. Désolé, c'est la première fois que je touche à github donc je ne comprend pas encore bien tout ce que je fais...

2023-05-02 10:16 UTC, cpinte commented
Salut, 
Ca a l'air tout bon cette fois. Je merge des que le build passe. Merci !

2023-05-02 11:19 UTC, FMalaval commented
Normalement ça doit être bon ! Je n'avais pas vu cette erreur car ça compilait sans problème en local avec le compilateur intel.

2023-05-03 05:15 UTC, cpinte approved these changes

2023-05-03 05:15 UTC, cpinte commented
Merci !

2023-05-03 05:15 UTC, merged

2023-05-03 08:34 UTC, FMalaval commented
Ah mince, je n'avais pas vu qu'il restait ce problème de longue ligne... Merci pour la correction !