Combined matrix strategy in build action
cpinte/mcfost pull request #73
Opened 2023-09-15 08:30 UTC by bmsykes

Reorganised test-suite.yml so everything runs in a single job with just one matrix strategy for os, compiler and openMP flags. It's a bit neater now. I've also made a couple of small changes so file paths are consistent between both os's. 

I've turned off fail-fast to prevent errors in one job from cancelling the others. Sometimes this hides errors in other jobs until you fix the first one but I can turn in back on if that's preferred.

2023-09-18 01:44 UTC, conradtchan requested changes
Looks very nice and tidy!

2023-09-18 01:44 UTC, conradtchan commented on .github/workflows/test-suite.yml
It should be possible to pass the environment variables from one step to subsequent steps. That would allow us to run the intel setvars.sh script if `matrix.os == 'macos' && matrix.compiler == 'ifort'`, and then make the next step `make all` for all OS and compiler combinations, rather than having a duplicated `make all` for macos+ifort.

See: https://www.edwardthomson.com/blog/github_actions_15_sharing_data_between_steps.html

2023-09-18 02:36 UTC, dliptai commented on .github/workflows/test-suite.yml
Alternatively, we can just always do 
```
source /opt/intel/oneapi/setvars.sh || true
make all
```

2023-09-18 02:37 UTC, dliptai commented
Looks good!

I was thinking though, maybe we should just run the `install.sh` script in ALL cases. We've got cacheing set up, so may as well, and it will simply the logic quite a bit

2023-09-18 02:43 UTC, dliptai commented
> Looks good!
> 
> I was thinking though, maybe we should just run the `install.sh` script in ALL cases. We've got cacheing set up, so may as well, and it will simply the logic quite a bit

Looks like we have to install HDF5 from source with ifort now too anyway

2023-09-18 03:08 UTC, bmsykes commented
> Looks good!
> 
> I was thinking though, maybe we should just run the `install.sh` script in ALL cases. We've got cacheing set up, so may as well, and it will simply the logic quite a bit

This would mean making some changes to `install.sh` wouldn't it? Some additional flags to make sure the libraries aren't unneccesarily downloaded and installed if they're cached?

2023-09-18 04:48 UTC, bmsykes commented on .github/workflows/test-suite.yml
I got it working with David's suggestion (after some playing around with bash things)

2023-09-18 05:56 UTC, dliptai commented on .github/workflows/test-suite.yml
> +        shell: bash {0}
I think we still want `-e` though. Otherwise the workflow won't show an error if `make all` fails.
We just don't want pipefail

2023-09-20 01:32 UTC, dliptai requested changes

2023-09-20 01:32 UTC, dliptai commented on .github/workflows/test-suite.yml
> +          make all
To prevent this warning 
```
:: WARNING: setvars.sh has already been run. Skipping re-execution.
   To force a re-execution of setvars.sh, use the '--force' option.
   Using '--force' can result in excessive use of your environment variables.
```

We could do

```suggestion
        run: |
          [ ! "$SETVARS_COMPLETED" == 1 ] && test -f /opt/intel/oneapi/setvars.sh && . /opt/intel/oneapi/setvars.sh
          make all
```

2023-09-20 02:42 UTC, dliptai approved these changes
I think it's ready to merge! @cpinte @conradtchan

2023-09-20 02:44 UTC, cpinte approved these changes

2023-09-20 02:44 UTC, merged

2023-09-20 02:44 UTC, cpinte commented
Thanks !