Compiler benchmark
cpinte/mcfost pull request #74
Opened 2023-09-21 07:00 UTC by bmsykes

- Added a benchmark job
- Compiles with both gnu and intel and runs the discF_00500 test
- Timing information is output through the Actions log

2023-09-24 23:38 UTC, conradtchan requested changes
Aside from the comment, this looks good to me 👍

2023-09-24 23:38 UTC, conradtchan commented on .github/actions/benchmark/action.yml
> +# TODO: if any other runs fail then don't save benchmark results (if the benchmark somehow runs e.g. linux-only bug)
Looks like this has been implemented. Is it okay to remove this TODO comment?

2023-09-24 23:49 UTC, bmsykes commented on .github/actions/benchmark/action.yml
> +# TODO: if any other runs fail then don't save benchmark results (if the benchmark somehow runs e.g. linux-only bug)
Yep!

2023-09-25 00:32 UTC, conradtchan approved these changes

2023-09-25 00:38 UTC, dliptai approved these changes

2023-09-25 01:32 UTC, conradtchan commented
@cpinte This PR is ready, please feel free to merge it in if you're happy with the changes 🙂

2023-09-25 04:39 UTC, cpinte approved these changes

2023-09-25 04:39 UTC, merged

2023-09-25 04:40 UTC, cpinte commented
Thanks !